### PR TITLE
Update homepage to taskata.js.org

### PR DESCRIPTION
**Pull request by robhowell**

### CODE REVIEW

**Comment by robhowell** [comment]
Updated homepage URL specified in package.json to use the js.org domain, with no root folder in the path - should fix the current path problem in the deployed version.

**Comment by robhowell** [comment]
@F-Ruxton I wanted you to have a chance to see this before merging, but if you are happy with it then you can merge it straight to master - once it's merged and deployed then hopefully that will fix the deployed version of Taskata!

**Comment by F-Ruxton** [comment]
Looks good, should have known it would be simple :) Went down a rabbit hole reading about deployment! Thanks for helping!

**Comment by F-Ruxton** [comment]
It's up!  🎉 👍

**Pull request merged**
